apiVersion: v1
kind: ReplicationController
metadata:
  name: startd-app
spec:
  replicas: 1
  selector:
    app: startd-app
  template:
    metadata:
      name: startd-app
      labels:
        app: startd-app
    spec:
      containers:
      - name: startd-app
        image: startd-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: startd-app-svc
spec:
  type: NodePort
  selector:
    app: startd-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30008
